on:
  push:
    branches: [main]
  pull_request:
name: CI
jobs:
  flatpak-builder:
    name: "Flatpak Builder"
    runs-on: ubuntu-latest
    container:
      image: docker.io/bilelmoussaoui/flatpak-github-actions
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions@v2
    - repo: flatpak install -y flathub org.freedesktop.Sdk.Compat.i386//20.08 org.freedesktop.Sdk.Extension.toolchain-i386//20.08
      with:
        bundle: "Proton-6.1-GE-2.flatpak"
        manifest-path: "io.github.Proton-6.1-GE-2-wine.yml"
